eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/db_zxpense
    username: postgres
    password: postgres
    pool-size: 30
